/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Cliente;
import model.dao.ClienteDAO;

public final class TelaClientes extends javax.swing.JFrame {

    

    public TelaClientes()  
    {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        tabelaClientes.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
        //preencherTabela("select * from cliente order by nome_cliente");
    }
    
    public void readJTable() 
    {
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        modelo.setNumRows(0);
        ClienteDAO clidao = new ClienteDAO();

        for (Cliente cli : clidao.read()) {

            modelo.addRow(new Object[]{
                cli.getIdCliente(),
                cli.getNomeCli(),
                cli.getDataNasc(),
                cli.getRg(),
                cli.getCpf(),
                cli.getEnderecoCli(),
                cli.getBairro(),
                cli.getCidadeCli(),
                cli.getEstCli(),
                cli.getCepCli(),
                cli.getEmailCli(),
                cli.getTelefone(),
                cli.getCelular()                    
            });

        }

    }
    public void readJTableForDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        modelo.setNumRows(0);
        ClienteDAO clidao = new ClienteDAO();

        clidao.readForDesc(desc).stream().forEach((cli) -> {
            modelo.addRow(new Object[]{
                cli.getIdCliente(),
                cli.getNomeCli(),
                cli.getDataNasc(),
                cli.getRg(),
                cli.getCpf(),
                cli.getEnderecoCli(),
                cli.getBairro(),
                cli.getCidadeCli(),
                cli.getEstCli(),
                cli.getCepCli(),
                cli.getEmailCli(),
                cli.getTelefone(),
                cli.getCelular()   
            });
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pesq = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        novoCliente = new javax.swing.JButton();
        removeCliente = new javax.swing.JButton();
        alterarCliente = new javax.swing.JButton();
        buscaCli = new javax.swing.JTextField();
        pesqClientes = new javax.swing.JButton();
        detalhesCli = new javax.swing.JPanel();
        alterarDadosCliente = new javax.swing.JButton();
        celCli = new javax.swing.JFormattedTextField();
        telCli = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        emailCli = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cidadeCli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        estadoCli = new javax.swing.JTextField();
        cepCli = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        bairroCli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        endCli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nomeCli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rgCli = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        cpfCli = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        dataNasc = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "CLIENTES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("MS Reference Sans Serif", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        pesq.setBackground(new java.awt.Color(0, 153, 255));
        pesq.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Clientes Cadastrados no Sistema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("MS Reference Sans Serif", 2, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        tabelaClientes.setAutoCreateRowSorter(true);
        tabelaClientes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Nasc", "RG", "CPF", "Endereço", "Bairro", "Cidade", "UF", "CEP", "E-Mail", "Telefone", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaClientes.setSelectionBackground(new java.awt.Color(51, 153, 255));
        tabelaClientes.getTableHeader().setResizingAllowed(false);
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
        tabelaClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaClientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaClientes);
        if (tabelaClientes.getColumnModel().getColumnCount() > 0) {
            tabelaClientes.getColumnModel().getColumn(0).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabelaClientes.getColumnModel().getColumn(1).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(2).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(2).setPreferredWidth(20);
            tabelaClientes.getColumnModel().getColumn(3).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(4).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(5).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(6).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(7).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(8).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(8).setPreferredWidth(0);
            tabelaClientes.getColumnModel().getColumn(9).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(9).setPreferredWidth(30);
            tabelaClientes.getColumnModel().getColumn(10).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(11).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(11).setPreferredWidth(30);
            tabelaClientes.getColumnModel().getColumn(12).setResizable(false);
            tabelaClientes.getColumnModel().getColumn(12).setPreferredWidth(30);
        }

        novoCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        novoCliente.setText("Novo");
        novoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoClienteActionPerformed(evt);
            }
        });

        removeCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        removeCliente.setText("Remover");
        removeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeClienteActionPerformed(evt);
            }
        });

        alterarCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alterarCliente.setText("Alterar");
        alterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarClienteActionPerformed(evt);
            }
        });

        buscaCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscaCli.setForeground(new java.awt.Color(102, 102, 102));
        buscaCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buscaCli.setToolTipText("Buscar produtos disponíveis em estoque");
        buscaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaCliActionPerformed(evt);
            }
        });

        pesqClientes.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        pesqClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lupa.png"))); // NOI18N
        pesqClientes.setText("Pesquisa de Clientes");
        pesqClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqClientesActionPerformed(evt);
            }
        });

        detalhesCli.setBackground(new java.awt.Color(0, 153, 255));
        detalhesCli.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alterar Dados do Cliente Selecionado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        detalhesCli.setForeground(new java.awt.Color(255, 255, 255));

        alterarDadosCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alterarDadosCliente.setText("Alterar Dados");
        alterarDadosCliente.setEnabled(false);
        alterarDadosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarDadosClienteActionPerformed(evt);
            }
        });

        try {
            celCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        celCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        celCli.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        celCli.setEnabled(false);
        celCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        celCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celCliActionPerformed(evt);
            }
        });

        try {
            telCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telCli.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        telCli.setEnabled(false);
        telCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Telefone Residencial:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Celular:");

        emailCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailCli.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        emailCli.setEnabled(false);
        emailCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCliActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("E-mail:");

        cidadeCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cidadeCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cidadeCli.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cidadeCli.setEnabled(false);
        cidadeCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeCliActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cidade:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Estado:");

        estadoCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        estadoCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        estadoCli.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        estadoCli.setEnabled(false);
        estadoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoCliActionPerformed(evt);
            }
        });

        try {
            cepCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cepCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cepCli.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cepCli.setEnabled(false);
        cepCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CEP:");

        bairroCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bairroCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bairroCli.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        bairroCli.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bairro:");

        endCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        endCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        endCli.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        endCli.setEnabled(false);
        endCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endCliActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Endereço:");

        nomeCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeCli.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nomeCli.setEnabled(false);
        nomeCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nome Completo:");

        try {
            rgCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rgCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rgCli.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rgCli.setEnabled(false);
        rgCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RG:");

        try {
            cpfCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpfCli.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cpfCli.setEnabled(false);
        cpfCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CPF:");

        try {
            dataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataNasc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataNasc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        dataNasc.setEnabled(false);
        dataNasc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Data Nasc:");

        javax.swing.GroupLayout detalhesCliLayout = new javax.swing.GroupLayout(detalhesCli);
        detalhesCli.setLayout(detalhesCliLayout);
        detalhesCliLayout.setHorizontalGroup(
            detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalhesCliLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detalhesCliLayout.createSequentialGroup()
                        .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detalhesCliLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(cepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detalhesCliLayout.createSequentialGroup()
                                .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(detalhesCliLayout.createSequentialGroup()
                                        .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailCli, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(telCli, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(30, 30, 30))
                                    .addGroup(detalhesCliLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(estadoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(139, 139, 139)))
                                .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(celCli, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(67, 67, 67))
                    .addGroup(detalhesCliLayout.createSequentialGroup()
                        .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endCli, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detalhesCliLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(409, 409, 409))
                            .addGroup(detalhesCliLayout.createSequentialGroup()
                                .addComponent(bairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(detalhesCliLayout.createSequentialGroup()
                .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detalhesCliLayout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(alterarDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detalhesCliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(rgCli, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(detalhesCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detalhesCliLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(227, 227, 227))
        );
        detalhesCliLayout.setVerticalGroup(
            detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalhesCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detalhesCliLayout.createSequentialGroup()
                        .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detalhesCliLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(dataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfCli)
                    .addComponent(rgCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(detalhesCliLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(estadoCli)))
                        .addGroup(detalhesCliLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8))
                .addGap(12, 12, 12)
                .addGroup(detalhesCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detalhesCliLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(celCli, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detalhesCliLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detalhesCliLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telCli, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(alterarDadosCliente)
                .addContainerGap())
        );

        sair.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sair.setText("Voltar");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pesqLayout = new javax.swing.GroupLayout(pesq);
        pesq.setLayout(pesqLayout);
        pesqLayout.setHorizontalGroup(
            pesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pesqLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(pesqClientes)
                .addGap(18, 18, 18)
                .addComponent(buscaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pesqLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(novoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(alterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
            .addGroup(pesqLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(detalhesCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 117, Short.MAX_VALUE))
        );
        pesqLayout.setVerticalGroup(
            pesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesqLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pesqClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoCliente)
                    .addComponent(removeCliente)
                    .addComponent(alterarCliente)
                    .addComponent(sair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detalhesCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pesq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pesq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesqClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqClientesActionPerformed
        readJTableForDesc(buscaCli.getText());
    }//GEN-LAST:event_pesqClientesActionPerformed

    private void alterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarClienteActionPerformed
        if (tabelaClientes.getSelectedRow() != -1) 
        {
            alterarDadosCliente.setEnabled(true);
            detalhesCli.setEnabled(true);
            nomeCli.setEnabled(true);
            dataNasc.setEnabled(true);
            rgCli.setEnabled(true);
            cpfCli.setEnabled(true);
            endCli.setEnabled(true);
            bairroCli.setEnabled(true);
            cidadeCli.setEnabled(true);
            estadoCli.setEnabled(true);
            cepCli.setEnabled(true);
            emailCli.setEnabled(true);
            telCli.setEnabled(true);
            celCli.setEnabled(true);
            nomeCli.grabFocus();
        }
        else
            JOptionPane.showMessageDialog(null, "Nenhum item da tabela foi selecionado para alteração! ");
    }//GEN-LAST:event_alterarClienteActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_sairActionPerformed

    private void removeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeClienteActionPerformed
        //        System.out.println("Linha selecionada: "+jTProdutos.getSelectedRow());
        if (tabelaClientes.getSelectedRow() != -1) {

            Cliente cli = new Cliente();
            ClienteDAO clidao = new ClienteDAO();

           cli.setIdCliente((int) tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 0));

            clidao.delete(cli);

            readJTable();
            
            nomeCli.setText("");
            dataNasc.setText("");
            rgCli.setText("");
            cpfCli.setText("");
            endCli.setText("");
            bairroCli.setText("");
            cidadeCli.setText("");
            estadoCli.setText("");
            cepCli.setText("");
            emailCli.setText("");
            telCli.setText("");
            celCli.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Nenhum cliente foi selecionado para exclusão!");
        }
    }//GEN-LAST:event_removeClienteActionPerformed

    private void novoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoClienteActionPerformed
        //chama a tela CadastrarCliente
        dispose();
        new CadastrarCliente().setVisible(true);
    }//GEN-LAST:event_novoClienteActionPerformed

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        if (tabelaClientes.getSelectedRow() != -1) {
            
            nomeCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 1).toString());
            dataNasc.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 2).toString());
            rgCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 3).toString());
            cpfCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 4).toString());
            endCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 5).toString());
            bairroCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 6).toString());
            cidadeCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 7).toString());
            estadoCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 8).toString());
            cepCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 9).toString());
            emailCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 10).toString());
            telCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 11).toString());
            celCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 12).toString());

        }
    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void alterarDadosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarDadosClienteActionPerformed
            if (tabelaClientes.getSelectedRow() != -1) 
            {
                  if (nomeCli.getText().equals(""))
            {
                 JOptionPane.showMessageDialog(null, "O nome do cliente não foi informado!");
                 nomeCli.grabFocus();
             }
             else if (dataNasc.getText().equals("  /  /    "))
            {
                 JOptionPane.showMessageDialog(null, "A data de nascimento não foi informada!!");
                 dataNasc.grabFocus();
             }
            else if (rgCli.getText().equals("  .   .   - "))
            {
                 JOptionPane.showMessageDialog(null, "O RG do cliente não foi informado!");
                 rgCli.grabFocus();
             }
            else if (cpfCli.getText().equals("   .   .   -  "))
            {
                 JOptionPane.showMessageDialog(null, "O CPF do cliente não foi informado!");
                 cpfCli.grabFocus();
             }
            else if (endCli.getText().equals(""))
            {
                 JOptionPane.showMessageDialog(null, "O endereço não foi informado!");
                 endCli.grabFocus();
             }
            else if (bairroCli.getText().equals(""))
            {
                 JOptionPane.showMessageDialog(null, "O bairro não foi informado!");
                 bairroCli.grabFocus();
             }
            else if (cidadeCli.getText().equals(""))
            {
                 JOptionPane.showMessageDialog(null, "A Cidade  não foi informada!");
                 cidadeCli.grabFocus();
             }
            else if (estadoCli.getText().equals(""))
            {
                 JOptionPane.showMessageDialog(null, "O Estado  não foi informado!");
                 estadoCli.grabFocus();
             }
            else if (cepCli.getText().equals("     -   "))
            {
                 JOptionPane.showMessageDialog(null, "O CEP não foi informado!");
                 cepCli.grabFocus();
             }
            else if (emailCli.getText().equals(""))
            {
                 JOptionPane.showMessageDialog(null, "O E-Mail do cliente não foi informado!");
                 emailCli.grabFocus();
             }
            else if ((celCli.getText().equals("(  )     -    ")) && (telCli.getText().equals("(  )    -    ")))
            {
                 JOptionPane.showMessageDialog(null, "Deve haver pelo menos um número de contato preenchido!");
                 telCli.grabFocus();
             }
             else
             {
                    Cliente cli = new Cliente();
                    ClienteDAO clidao = new ClienteDAO();

                    
                    cli.setNomeCli(nomeCli.getText());
                    cli.setDataNasc(dataNasc.getText());
                    cli.setRg(rgCli.getText());
                    cli.setCpf(cpfCli.getText());
                    cli.setEnderecoCli(endCli.getText());
                    cli.setBairro(bairroCli.getText());
                    cli.setCidadeCli(cidadeCli.getText());
                    cli.setEstCli(estadoCli.getText());
                    cli.setCepCli(cepCli.getText());
                    cli.setEmailCli(emailCli.getText());
                    cli.setTelefone(telCli.getText());
                    cli.setCelular(celCli.getText());
                    cli.setIdCliente((int) tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 0));

                    clidao.update(cli);

                        nomeCli.setText("");
                        dataNasc.setText("");
                        rgCli.setText("");
                        cpfCli.setText("");
                        endCli.setText("");
                        bairroCli.setText("");
                        cidadeCli.setText("");
                        estadoCli.setText("");
                        cepCli.setText("");
                        emailCli.setText("");
                        telCli.setText("");
                        celCli.setText("");

                        
                        nomeCli.setEnabled(false);
                        dataNasc.setEnabled(false);
                        rgCli.setEnabled(false);
                        cpfCli.setEnabled(false);
                        endCli.setEnabled(false);
                        bairroCli.setEnabled(false);
                        cidadeCli.setEnabled(false);
                        estadoCli.setEnabled(false);
                        cepCli.setEnabled(false);
                        emailCli.setEnabled(false);
                        telCli.setEnabled(false);
                        celCli.setEnabled(false);
                        alterarDadosCliente.setEnabled(false);


                        readJTable();
                    }
            }
    }//GEN-LAST:event_alterarDadosClienteActionPerformed

    private void tabelaClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaClientesKeyReleased
        if (tabelaClientes.getSelectedRow() != -1) {

            nomeCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 1).toString());
            dataNasc.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 2).toString());
            rgCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 3).toString());
            cpfCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 4).toString());
            endCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 5).toString());
            bairroCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 6).toString());
            cidadeCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 7).toString());
            estadoCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 8).toString());
            cepCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 9).toString());
            emailCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 10).toString());
            telCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 11).toString());
            celCli.setText(tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 12).toString());

        }
    }//GEN-LAST:event_tabelaClientesKeyReleased

    private void buscaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaCliActionPerformed

    private void celCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celCliActionPerformed

    private void emailCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailCliActionPerformed

    private void cidadeCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeCliActionPerformed

    private void estadoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoCliActionPerformed

    private void endCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endCliActionPerformed

    private void nomeCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCliActionPerformed

    }//GEN-LAST:event_nomeCliActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new TelaClientes().setVisible(true);
                
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarCliente;
    private javax.swing.JButton alterarDadosCliente;
    private javax.swing.JTextField bairroCli;
    private javax.swing.JTextField buscaCli;
    private javax.swing.JFormattedTextField celCli;
    private javax.swing.JFormattedTextField cepCli;
    private javax.swing.JTextField cidadeCli;
    private javax.swing.JFormattedTextField cpfCli;
    private javax.swing.JFormattedTextField dataNasc;
    private javax.swing.JPanel detalhesCli;
    private javax.swing.JTextField emailCli;
    private javax.swing.JTextField endCli;
    private javax.swing.JTextField estadoCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeCli;
    private javax.swing.JButton novoCliente;
    private javax.swing.JPanel pesq;
    private javax.swing.JButton pesqClientes;
    private javax.swing.JButton removeCliente;
    private javax.swing.JFormattedTextField rgCli;
    private javax.swing.JButton sair;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JFormattedTextField telCli;
    // End of variables declaration//GEN-END:variables
}
