/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Produto;
import model.dao.ProdutoDAO;

public final class TelaProdutos extends javax.swing.JFrame {

    

    public TelaProdutos()  
    {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
        tabelaProdutos.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
        //preencherTabela("select * from produto order by id_produto");
    }
    
    public void readJTable() 
    {
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();

        for (Produto p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getPrecoCusto(),
                p.getPrecoVenda(),
                p.getQtd()
            });

        }

    }
    public void readJTableForDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();

        pdao.readForDesc(desc).stream().forEach((p) -> {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getPrecoCusto(),
                p.getPrecoVenda(),
                p.getQtd()
            });
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pesq = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        novoProd = new javax.swing.JButton();
        removeProd = new javax.swing.JButton();
        alterarProd = new javax.swing.JButton();
        buscaProd = new javax.swing.JTextField();
        pesqButton = new javax.swing.JButton();
        detalhesProd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        altDescProd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        altPrecoCusto = new javax.swing.JTextField();
        altPrecoVenda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        altQtd = new javax.swing.JTextField();
        alterarDadosProd = new javax.swing.JButton();
        sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "PRODUTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("MS Reference Sans Serif", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        pesq.setBackground(new java.awt.Color(0, 153, 255));
        pesq.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos em Estoque", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("MS Reference Sans Serif", 2, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        tabelaProdutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Preço de Custo", "Preço de Venda", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.setSelectionBackground(new java.awt.Color(51, 153, 255));
        tabelaProdutos.getTableHeader().setResizingAllowed(false);
        tabelaProdutos.getTableHeader().setReorderingAllowed(false);
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        tabelaProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaProdutosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);
        if (tabelaProdutos.getColumnModel().getColumnCount() > 0) {
            tabelaProdutos.getColumnModel().getColumn(0).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(1).setResizable(false);
        }

        novoProd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        novoProd.setText("Novo");
        novoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoProdActionPerformed(evt);
            }
        });

        removeProd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        removeProd.setText("Remover");
        removeProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProdActionPerformed(evt);
            }
        });

        alterarProd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alterarProd.setText("Alterar");
        alterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarProdActionPerformed(evt);
            }
        });

        buscaProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscaProd.setForeground(new java.awt.Color(102, 102, 102));
        buscaProd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buscaProd.setToolTipText("Buscar produtos disponíveis em estoque");
        buscaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaProdActionPerformed(evt);
            }
        });

        pesqButton.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        pesqButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lupa.png"))); // NOI18N
        pesqButton.setText("Pesquisar Produtos");
        pesqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqButtonActionPerformed(evt);
            }
        });

        detalhesProd.setBackground(new java.awt.Color(0, 153, 255));
        detalhesProd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alterar Dados do Produto Selecionado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        detalhesProd.setForeground(new java.awt.Color(255, 255, 255));
        detalhesProd.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Descrição:");

        altDescProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        altDescProd.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Preço de Custo:");

        altPrecoCusto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        altPrecoCusto.setEnabled(false);

        altPrecoVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        altPrecoVenda.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Preço de Venda:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quant:");

        altQtd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        altQtd.setEnabled(false);

        alterarDadosProd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alterarDadosProd.setText("Alterar Dados");
        alterarDadosProd.setEnabled(false);
        alterarDadosProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarDadosProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detalhesProdLayout = new javax.swing.GroupLayout(detalhesProd);
        detalhesProd.setLayout(detalhesProdLayout);
        detalhesProdLayout.setHorizontalGroup(
            detalhesProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalhesProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detalhesProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalhesProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(altDescProd, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(detalhesProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detalhesProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(altPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
            .addGroup(detalhesProdLayout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(alterarDadosProd, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detalhesProdLayout.setVerticalGroup(
            detalhesProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalhesProdLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(detalhesProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(altDescProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(altPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detalhesProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(altQtd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alterarDadosProd)
                .addContainerGap())
        );

        sair.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sair.setText("Voltar");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pesqLayout = new javax.swing.GroupLayout(pesq);
        pesq.setLayout(pesqLayout);
        pesqLayout.setHorizontalGroup(
            pesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesqLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buscaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
            .addGroup(pesqLayout.createSequentialGroup()
                .addGroup(pesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pesqLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(detalhesProd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pesqLayout.createSequentialGroup()
                                .addComponent(novoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alterarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pesqLayout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(pesqButton)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        pesqLayout.setVerticalGroup(
            pesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesqLayout.createSequentialGroup()
                .addComponent(buscaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesqButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoProd)
                    .addComponent(removeProd)
                    .addComponent(alterarProd)
                    .addComponent(sair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(detalhesProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pesq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqButtonActionPerformed
        readJTableForDesc(buscaProd.getText());
    }//GEN-LAST:event_pesqButtonActionPerformed

    private void alterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarProdActionPerformed
        if (tabelaProdutos.getSelectedRow() != -1) 
        {
            alterarDadosProd.setEnabled(true);
            detalhesProd.setEnabled(true);
            altDescProd.setEnabled(true);
            altPrecoCusto.setEnabled(true);
            altPrecoVenda.setEnabled(true);
            altQtd.setEnabled(true);
            altDescProd.grabFocus();
        }
        else
            JOptionPane.showMessageDialog(null, "Nenhum item da tabela foi selecionado para alteração! ");
    }//GEN-LAST:event_alterarProdActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();
        new TelaPrincipal().setVisible(true);
    }//GEN-LAST:event_sairActionPerformed

    private void removeProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProdActionPerformed
        //        System.out.println("Linha selecionada: "+jTProdutos.getSelectedRow());
        if (tabelaProdutos.getSelectedRow() != -1) {

            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();

            p.setId((int) tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 0));

            dao.delete(p);

            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
    }//GEN-LAST:event_removeProdActionPerformed

    private void novoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoProdActionPerformed
        //chama a tela cadastrarProduto
        dispose();
        new CadastrarProduto().setVisible(true);
    }//GEN-LAST:event_novoProdActionPerformed

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
        if (tabelaProdutos.getSelectedRow() != -1) {

            altDescProd.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 1).toString());
            altPrecoCusto.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 2).toString());
            altPrecoVenda.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 3).toString());
            altQtd.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_tabelaProdutosMouseClicked

    private void alterarDadosProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarDadosProdActionPerformed
            if (tabelaProdutos.getSelectedRow() != -1) 
            {
                if (altDescProd.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(null, "O campo de descrição deve ser preenchido!");
                    altDescProd.grabFocus();
                }
                else if (altPrecoCusto.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(null, "O preço de custo deve ser preenchido!");
                    altPrecoCusto.grabFocus();
                }
                else if (altPrecoVenda.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(null, "O preço de venda deve ser preenchido!");
                    altPrecoVenda.grabFocus();
                }
                else if (altQtd.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(null, "A quantidade deve ser preenchida!");
                    altQtd.grabFocus();
                }
                else
                {
                    Produto p = new Produto();
                    ProdutoDAO dao = new ProdutoDAO();

                    p.setDescricao(altDescProd.getText());
                    p.setPrecoCusto(Double.parseDouble(altPrecoCusto.getText()));
                    p.setPrecoVenda(Double.parseDouble(altPrecoVenda.getText()));
                    p.setQtd(Integer.parseInt(altQtd.getText()));
                    p.setId((int) tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 0));

                    dao.update(p);

                    altDescProd.setText("");
                    altPrecoCusto.setText("");
                    altPrecoVenda.setText("");
                    altQtd.setText("");

                    detalhesProd.setEnabled(false);
                    altDescProd.setEnabled(false);
                    altPrecoCusto.setEnabled(false);
                    altPrecoVenda.setEnabled(false);
                    altQtd.setEnabled(false);
                    alterarDadosProd.setEnabled(false);
                    

                    readJTable();
                }
        }
    }//GEN-LAST:event_alterarDadosProdActionPerformed

    private void tabelaProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaProdutosKeyReleased
        if (tabelaProdutos.getSelectedRow() != -1) {

            altDescProd.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 1).toString());
            altPrecoCusto.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 2).toString());
            altPrecoVenda.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 3).toString());
            altQtd.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_tabelaProdutosKeyReleased

    private void buscaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaProdActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new TelaProdutos().setVisible(true);
                
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altDescProd;
    private javax.swing.JTextField altPrecoCusto;
    private javax.swing.JTextField altPrecoVenda;
    private javax.swing.JTextField altQtd;
    private javax.swing.JButton alterarDadosProd;
    private javax.swing.JButton alterarProd;
    private javax.swing.JTextField buscaProd;
    private javax.swing.JPanel detalhesProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novoProd;
    private javax.swing.JPanel pesq;
    private javax.swing.JButton pesqButton;
    private javax.swing.JButton removeProd;
    private javax.swing.JButton sair;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
