/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Produto;
import model.dao.ProdutoDAO;

/**
 *
 * @author DougliitOs
 */
public class TelaPrincipal extends javax.swing.JFrame {

    
    
    public TelaPrincipal()
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        botaoProdutos = new javax.swing.JButton();
        botaoClientes = new javax.swing.JButton();
        botaoVendas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();
        botaoForn = new javax.swing.JButton();
        botaoCompras = new javax.swing.JButton();
        botaoRelatorios = new javax.swing.JButton();
        botaoServicos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "CONNECT - TELA INICIAL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("MS Reference Sans Serif", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 51));

        botaoProdutos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botaoProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/produtoIco (2).png"))); // NOI18N
        botaoProdutos.setText("Produtos");
        botaoProdutos.setToolTipText("Consulte e adicione produtos ao seu estoque.");
        botaoProdutos.setAlignmentX(0.5F);
        botaoProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoProdutos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botaoProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProdutosActionPerformed(evt);
            }
        });

        botaoClientes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botaoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cliente.png"))); // NOI18N
        botaoClientes.setText("Clientes");
        botaoClientes.setToolTipText("Consulte e adicione produtos ao seu estoque.");
        botaoClientes.setAlignmentX(0.5F);
        botaoClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoClientes.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botaoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClientesActionPerformed(evt);
            }
        });

        botaoVendas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botaoVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dinheiro.png"))); // NOI18N
        botaoVendas.setText("Vendas");
        botaoVendas.setToolTipText("Consulte e adicione produtos ao seu estoque.");
        botaoVendas.setAlignmentX(0.5F);
        botaoVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoVendas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botaoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVendasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 200)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo vetor.png"))); // NOI18N

        botaoSair.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        botaoSair.setText("Sair");
        botaoSair.setToolTipText("Consulte e adicione produtos ao seu estoque.");
        botaoSair.setAlignmentX(0.5F);
        botaoSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoSair.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoForn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        botaoForn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fornecedor.png"))); // NOI18N
        botaoForn.setText("Fornecedores");
        botaoForn.setToolTipText("Consulte e adicione produtos ao seu estoque.");
        botaoForn.setAlignmentX(0.5F);
        botaoForn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoForn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botaoForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFornActionPerformed(evt);
            }
        });

        botaoCompras.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botaoCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/compras.png"))); // NOI18N
        botaoCompras.setText("Compras");
        botaoCompras.setToolTipText("Consulte e adicione produtos ao seu estoque.");
        botaoCompras.setAlignmentX(0.5F);
        botaoCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoCompras.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botaoCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComprasActionPerformed(evt);
            }
        });

        botaoRelatorios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botaoRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorios.png"))); // NOI18N
        botaoRelatorios.setText("Relatórios");
        botaoRelatorios.setToolTipText("Consulte e adicione produtos ao seu estoque.");
        botaoRelatorios.setAlignmentX(0.5F);
        botaoRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoRelatorios.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botaoRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRelatoriosActionPerformed(evt);
            }
        });

        botaoServicos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botaoServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/serviços.png"))); // NOI18N
        botaoServicos.setText("Serviços");
        botaoServicos.setToolTipText("Consulte e adicione produtos ao seu estoque.");
        botaoServicos.setAlignmentX(0.5F);
        botaoServicos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoServicos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        botaoServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoServicosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoVendas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoForn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoForn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoServicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProdutosActionPerformed
            dispose();
            new TelaProdutos().setVisible(true);
        
    }//GEN-LAST:event_botaoProdutosActionPerformed

    private void botaoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoClientesActionPerformed
            dispose();
            new TelaClientes().setVisible(true);
    }//GEN-LAST:event_botaoClientesActionPerformed

    private void botaoVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVendasActionPerformed
        dispose();
        new TelaVendas().setVisible(true);
    }//GEN-LAST:event_botaoVendasActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        int confirm;
        
        confirm = JOptionPane.showConfirmDialog(null, "Deseja realmente sair do programa? ");
        
        if (JOptionPane.YES_OPTION == confirm)
        {
            //System.exit(0);
            dispose();
            new TelaLogin().setVisible(true);
        }    
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoFornActionPerformed

    private void botaoComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoComprasActionPerformed

    private void botaoRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRelatoriosActionPerformed

    private void botaoServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoServicosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoClientes;
    private javax.swing.JButton botaoCompras;
    private javax.swing.JButton botaoForn;
    private javax.swing.JButton botaoProdutos;
    private javax.swing.JButton botaoRelatorios;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoServicos;
    private javax.swing.JButton botaoVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables
}
