/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.ConectaBanco2;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.ModeloTabela;
import model.bean.Produto;
import model.bean.ModeloVenda;
import model.dao.ControleVenda;
import model.dao.ProdutoDAO;

/**
 *
 * @author DougliitOs
 */
public class TelaVendas extends javax.swing.JFrame {

    ConectaBanco2 conn = new ConectaBanco2();
    ModeloVenda modvenda = new ModeloVenda();
    ControleVenda control = new ControleVenda();
    double precoProduto;
    int qtdItemVenda, codVenda;
   
    
    public TelaVendas() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
       
        DefaultTableModel modelo = (DefaultTableModel) tabelaItensVenda.getModel();
        tabelaItensVenda.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
        
    }
    
    public void readJTable() 
    {
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaPesqProd.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();

        for (Produto p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getDescricao(),
                p.getPrecoVenda(),
                p.getQtd()
            });

        }

    }
    
     public void preencherTabelaItensVenda(String sql) throws SQLException 
     {
         ArrayList dados = new ArrayList();
         
         String[] Colunas = new String[] {"Descrição","Quantidade","Valor Total"};
         conn.conexao();
         conn.executaSQL(sql);
         try{
             conn.rs.first();
             do{
                 float valorProduto = conn.rs.getFloat("preco_venda");
                 int qtdVendida = conn.rs.getInt("qtd_produto_venda");
                 dados.add(new Object[]{conn.rs.getString("descricao_produto"), conn.rs.getString("qtd_produto_venda"), valorProduto*qtdVendida});
             } while(conn.rs.next());
             
         } catch (SQLException ex){
             JOptionPane.showMessageDialog(null, "Erro ao preencher a lista de Itens da venda! \nErro: "+ex);
         }
         
         ModeloTabela modelo = new ModeloTabela(dados, Colunas);
         tabelaItensVenda.setModel(modelo);
         /*
         tabelaItensVenda.getColumnModel().getColumn(0).setPreferredWidth(100);
         tabelaItensVenda.getColumnModel().getColumn(0).setResizable(false);
         tabelaItensVenda.getColumnModel().getColumn(1).setPreferredWidth(100);
         tabelaItensVenda.getColumnModel().getColumn(1).setResizable(false);
         tabelaItensVenda.getColumnModel().getColumn(2).setPreferredWidth(100);
         tabelaItensVenda.getColumnModel().getColumn(2).setResizable(false);
         tabelaItensVenda.setAutoResizeMode(tabelaItensVenda.AUTO_RESIZE_OFF);
         tabelaItensVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         */
         
     }
         

    
    

    public void readJTableForDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaPesqProd.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();

        pdao.readForDesc(desc).stream().forEach((p) -> {
            modelo.addRow(new Object[]{
                p.getDescricao(),
                p.getPrecoVenda(),
                p.getQtd()
            });
        });

    }
    
    /* METODO DE PREENCHER TABELA RELATIVO AO TUTORIAL DE EXEMPLO
    public void preencherTabelaProduto(String sql) throws SQLException
    {
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[] {"Código", "Descrição", "Quant"};
        conn.conexao();
        conn.executaSQL(sql);
        try{
            conn.rs.first();
        }catch(SQLException ex){
            
        }
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeProd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dataVenda = new javax.swing.JFormattedTextField();
        buscaProd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        valorItem = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        fechaVenda = new javax.swing.JButton();
        cancelaVenda = new javax.swing.JButton();
        addItem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        valorTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaItensVenda = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPesqProd = new javax.swing.JTable();
        qtdItem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Vendas - Connect");
        setBackground(new java.awt.Color(51, 153, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Formulário De Vendas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data");

        nomeProd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomeProd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProdActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Produto");

        try {
            dataVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataVenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dataVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataVendaFocusGained(evt);
            }
        });
        dataVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataVendaActionPerformed(evt);
            }
        });

        buscaProd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buscaProd.setText("Busca");
        buscaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaProdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quant");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor por Item");

        valorItem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        valorItem.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valorItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valorItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                valorItemFocusGained(evt);
            }
        });
        valorItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorItemActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tabela de Pesquisa de Produtos");

        fechaVenda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fechaVenda.setText("Finalizar Venda");
        fechaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaVendaActionPerformed(evt);
            }
        });

        cancelaVenda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelaVenda.setText("Cancelar Venda");
        cancelaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaVendaActionPerformed(evt);
            }
        });

        addItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addItem.setText("Add Item");
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));

        valorTotal.setBackground(new java.awt.Color(153, 255, 204));
        valorTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Valor Total:");

        tabelaItensVenda.setAutoCreateRowSorter(true);
        tabelaItensVenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelaItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Quant", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaItensVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaItensVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaItensVenda);
        if (tabelaItensVenda.getColumnModel().getColumnCount() > 0) {
            tabelaItensVenda.getColumnModel().getColumn(1).setPreferredWidth(1);
        }

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 102));
        jLabel8.setText("Itens da Venda");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(22, 22, 22))
        );

        tabelaPesqProd.setAutoCreateRowSorter(true);
        tabelaPesqProd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelaPesqProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Preço", "Quant. em Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPesqProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPesqProdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaPesqProd);
        if (tabelaPesqProd.getColumnModel().getColumnCount() > 0) {
            tabelaPesqProd.getColumnModel().getColumn(1).setHeaderValue("Valor Unit.");
            tabelaPesqProd.getColumnModel().getColumn(2).setPreferredWidth(1);
        }

        qtdItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qtdItem.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qtdItem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qtdItemFocusGained(evt);
            }
        });
        qtdItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valorItem)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(qtdItem))
                        .addGap(59, 59, 59)
                        .addComponent(addItem)
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(dataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(nomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(buscaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(fechaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cancelaVenda)
                        .addGap(294, 294, 294))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscaProd)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(qtdItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(valorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addComponent(addItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fechaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaVendaActionPerformed

    private void cancelaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaVendaActionPerformed

        int confirm;
        
        confirm = JOptionPane.showConfirmDialog(null, "Tem certeza que quer cancelar a venda? \nTodos os dados registrados não serão salvos. ");
        
        if (JOptionPane.YES_OPTION == confirm)
        {
            dispose();
            new TelaPrincipal().setVisible(true);
        }   
    }//GEN-LAST:event_cancelaVendaActionPerformed

    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed

        conn.conexao();
        
        modvenda.setNomeProd(nomeProd.getText());
        modvenda.setQtdItemVenda(Integer.parseInt(qtdItem.getText()));
        modvenda.setIdVenda(codVenda);
        try {
            control.adicionaItem(modvenda);
            preencherTabelaItensVenda("select * from produto inner join itensdavenda on produto.id_produto = itensdavenda.id_produto " +
            "inner join venda on venda.id_venda = itensdavenda.id_venda where venda.id_venda ="+codVenda);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao adicionar o item!");
        }
        
    }//GEN-LAST:event_addItemActionPerformed

    private void dataVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataVendaActionPerformed
        
    }//GEN-LAST:event_dataVendaActionPerformed

    private void buscaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaProdActionPerformed
         conn.conexao();
        
        try{
             PreparedStatement pst = conn.conn.prepareStatement("insert into venda (valor_venda) values(?)");
             pst.setFloat(1,0);
             pst.execute(); //insere uma nova venda no banco de dados
             conn.executaSQL("select * from venda");
             conn.rs.last();
             codVenda = conn.rs.getInt("id_venda");
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "ERRO: " + ex);
        }
        readJTableForDesc(nomeProd.getText());
    }//GEN-LAST:event_buscaProdActionPerformed

    private void nomeProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProdActionPerformed

    private void valorItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorItemActionPerformed
        
    }//GEN-LAST:event_valorItemActionPerformed

    private void tabelaItensVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaItensVendaMouseClicked
         //CONEXÃO COM O BANCO DANDO ERRO NA CONSULTA DO PREÇO
        /*
         conn.conexao();
        try{
            String nomeProduto = "" +  tabelaPesq.getValueAt(tabelaPesq.getSelectedRow(), 0);
            conn.executaSQL("select * from produto where descricao_produto= ' "+ nomeProduto + " ' ");
            conn.rs.first();
            precoProduto = conn.rs.getDouble("preco_venda");
            nomeProd.setText(nomeProduto);
            valorItem.setText(String.valueOf(precoProduto));
            qtdItem.setText("1");
            //conn.desconecta();
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao pesquisar o preço!");
        }
        */
        

         //CONEXÃO DA TABELA FUNCIONANDO OK 
            
        
    }//GEN-LAST:event_tabelaItensVendaMouseClicked

    private void valorItemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorItemFocusGained
        double total;
        total = Double.parseDouble(valorItem.getText()) * Integer.parseInt(qtdItem.getText());
        valorTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_valorItemFocusGained

    private void dataVendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataVendaFocusGained
        double total;
        total = Double.parseDouble(valorItem.getText()) * Integer.parseInt(qtdItem.getText());
        valorTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_dataVendaFocusGained

    private void tabelaPesqProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPesqProdMouseClicked
        conn.conexao();   
        try {
            String descProduto = "" + tabelaPesqProd.getValueAt(tabelaPesqProd.getSelectedRow(), 0);
            conn.executaSQL("select * from produto where descricao_produto = '"+descProduto+"'");
            conn.rs.first();
            precoProduto = conn.rs.getDouble("preco_venda");
            nomeProd.setText(descProduto);
            valorItem.setText(String.valueOf(precoProduto));
            qtdItem.setText("1");
            
            conn.desconecta();
            
            //nomeProd.setText(descProd);
            //precoProduto = Double.parseDouble(""  + tabelaPesqProd.getValueAt(tabelaPesqProd.getSelectedRow(), 1));
            //valorItem.setText(String.valueOf(precoProduto));
            //qtdItemVenda = Integer.parseInt("" +  tabelaPesqProd.getValueAt(tabelaPesqProd.getSelectedRow(), 2));
            //qtdItem.setText(Integer.parseInt.valueOf(1));
            //qtdItem.setText(String.valueOf(qtdItemVenda));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao pesquisar o preço!");
        }
    }//GEN-LAST:event_tabelaPesqProdMouseClicked

    private void qtdItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdItemActionPerformed

    private void qtdItemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtdItemFocusGained
        double total;
        total = Double.parseDouble(valorItem.getText()) * Integer.parseInt(qtdItem.getText());
        valorTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_qtdItemFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItem;
    private javax.swing.JButton buscaProd;
    private javax.swing.JButton cancelaVenda;
    private javax.swing.JFormattedTextField dataVenda;
    private javax.swing.JButton fechaVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomeProd;
    private javax.swing.JTextField qtdItem;
    private javax.swing.JTable tabelaItensVenda;
    private javax.swing.JTable tabelaPesqProd;
    private javax.swing.JFormattedTextField valorItem;
    private javax.swing.JTextField valorTotal;
    // End of variables declaration//GEN-END:variables
}
